export const jsonData = [
    {
      "layerType": 0,
      "thumb": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\thumb_file\\1693109746668_64e7e13bfd2d914a.jpg",
      "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\bg_file\\1693109746669_125ca3b92e0c51d3.jpg",
      "color": null,
      "width": 100,
      "height": 100,
      "type": "LayerKind.NORMAL",
      "gradAngle": 0,
      "gradRatio": 0,
      "animation": 0,
      "videoStartTime": 0,
      "videoEndTime": 0,
      "adjustment": {
        "black_point": 1,
        "brightness": 1,
        "brilliance": 1,
        "contrast": 1,
        "exposure": 1,
        "highlight": 1,
        "saturation": 1,
        "shadow": 1,
        "sharpness": 1,
        "tint": 1,
        "vibrance": 1,
        "blur": 0
      },
      "filter": {
        "intensity": 1,
        "type": 0
      },
      "crop": {
        "top": 0,
        "bottom": 0,
        "left": 0,
        "right": 0
      },
      "flip": {
        "h": false,
        "v": false
      },
      "layers": [
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746671_2ee94020c9c33c5b.png",
          "left": 303,
          "top": 2886,
          "originX": "left",
          "originY": "top",
          "width": 1875,
          "height": 730,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746672_0f0098797baa67d8.png",
          "left": 420,
          "top": 1712,
          "originX": "left",
          "originY": "top",
          "width": 1640,
          "height": 1361,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746673_7973bba467c92b4a.png",
          "left": -299,
          "top": 1923,
          "originX": "left",
          "originY": "top",
          "width": 681,
          "height": 1625,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746674_6185a100ed1824f0.png",
          "left": 2103,
          "top": 1923,
          "originX": "left",
          "originY": "top",
          "width": 681,
          "height": 1625,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746679_7683ec128e6e6df6.png",
          "left": 1853,
          "top": 3192,
          "originX": "left",
          "originY": "top",
          "width": 362,
          "height": 356,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746681_40533f62675003e0.png",
          "left": 171,
          "top": 3231,
          "originX": "left",
          "originY": "top",
          "width": 362,
          "height": 356,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746682_1e4cf3b51e1f67d4.png",
          "left": 341,
          "top": 2054,
          "originX": "left",
          "originY": "top",
          "width": 1728,
          "height": 1492,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746684_bd8b56970315eeec.png",
          "left": 0,
          "top": -15,
          "originX": "left",
          "originY": "top",
          "width": 2480,
          "height": 127,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746685_a567c45926845635.png",
          "left": 2386,
          "top": 64,
          "originX": "left",
          "originY": "top",
          "width": 94,
          "height": 1843,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746686_8d4f82b1a4e27272.png",
          "left": 0,
          "top": 64,
          "originX": "left",
          "originY": "top",
          "width": 94,
          "height": 1843,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746687_8b71b754b14948e8.png",
          "left": 2135,
          "top": 36,
          "originX": "left",
          "originY": "top",
          "width": 140,
          "height": 1019,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746688_deca1084178828b4.png",
          "left": 1914,
          "top": -90,
          "originX": "left",
          "originY": "top",
          "width": 92,
          "height": 1033,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746689_7887c539d9b4eac5.png",
          "left": 1629,
          "top": 35,
          "originX": "left",
          "originY": "top",
          "width": 189,
          "height": 788,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746690_b39f2b494ec3a6d1.png",
          "left": 1408,
          "top": -160,
          "originX": "left",
          "originY": "top",
          "width": 140,
          "height": 777,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746691_c4053071358aab73.png",
          "left": 1153,
          "top": -26,
          "originX": "left",
          "originY": "top",
          "width": 175,
          "height": 728,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746696_8fd6dd0a933545f1.png",
          "left": 932,
          "top": -160,
          "originX": "left",
          "originY": "top",
          "width": 140,
          "height": 777,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746700_cb92ba9303299a06.png",
          "left": 662,
          "top": 35,
          "originX": "left",
          "originY": "top",
          "width": 189,
          "height": 788,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746701_d42cf0c4bba21774.png",
          "left": 463,
          "top": -90,
          "originX": "left",
          "originY": "top",
          "width": 92,
          "height": 1033,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 1,
          "isVideo": false,
          "image": "C:\\NODE\\exam\\task - Copy - Copy\\uploads\\sticker_file\\1693109746702_ec560645818d33fe.png",
          "left": 194,
          "top": 36,
          "originX": "left",
          "originY": "top",
          "width": 140,
          "height": 1019,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "rotation": 0,
          "opacity": 100,
          "type": 0,
          "color": null,
          "resizeType": 0,
          "lockType": 0,
          "animation": 0,
          "adjustment": {
            "black_point": 1,
            "brightness": 1,
            "brilliance": 1,
            "contrast": 1,
            "exposure": 1,
            "highlight": 1,
            "saturation": 1,
            "shadow": 1,
            "sharpness": 1,
            "tint": 1,
            "vibrance": 1,
            "blur": 0
          },
          "filter": {
            "intensity": 1,
            "type": 0
          },
          "crop": {
            "top": 0,
            "bottom": 0,
            "left": 0,
            "right": 0
          },
          "flip": {
            "h": false,
            "v": false
          },
          "videoStartTime": 0,
          "videoEndTime": 0
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "You are cordinaly invited to the",
          "font": "Alice-Regular",
          "width": 1165.56921386719,
          "height": 94.8740730285645,
          "left": 658.215576171875,
          "top": 825.26617898462,
          "originX": "left",
          "originY": "top",
          "size": 14.1391123302986,
          "color": "#56490F",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "HALDI CEREMONY",
          "font": "Alice-Regular",
          "width": 979.195922851563,
          "height": 128.079986572266,
          "left": 751.965087890625,
          "top": 956.481037993409,
          "originX": "left",
          "originY": "top",
          "size": 19.0877993158495,
          "color": "#AD8E00",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "Nivya",
          "font": "TheHeartofEverythingDemo",
          "width": 416.508728027344,
          "height": 247.498313903809,
          "left": 714.18928527832,
          "top": 1094.39209451196,
          "originX": "left",
          "originY": "top",
          "size": 31.1060424665497,
          "color": "#7A0901",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "Mehul",
          "font": "TheHeartofEverythingDemo",
          "width": 462.940658569336,
          "height": 247.498313903809,
          "left": 1331.73265075684,
          "top": 1095.39209451196,
          "originX": "left",
          "originY": "top",
          "size": 31.1060424665497,
          "color": "#7A0901",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "&",
          "font": "AbhayaLibre-ExtraBold",
          "width": 100.76496887207,
          "height": 192.187488555908,
          "left": 1187.86889648438,
          "top": 1115.7582596731,
          "originX": "left",
          "originY": "top",
          "size": 28.9851758758997,
          "color": "#7A0901",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "12th June 2024",
          "font": "Alice-Regular",
          "width": 668.949890136719,
          "height": 118.592571258545,
          "left": 904.525146484375,
          "top": 1353.82017809724,
          "originX": "left",
          "originY": "top",
          "size": 17.6738865294505,
          "color": "#56490E",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        },
        {
          "layerType": 2,
          "isVideo": false,
          "text": "Maharaja farm, near lack garden\rMota varachha, Surat.",
          "font": "Alice-Regular",
          "width": 1081.78601074219,
          "height": 175.386657714844,
          "left": 698.107177734375,
          "top": 1502.60531908845,
          "originX": "left",
          "originY": "top",
          "size": 12.7251995438997,
          "color": "#56490E",
          "opacity": 100,
          "rotation": 0,
          "isEditable": 0,
          "isUrl": 0,
          "editableTitle": "",
          "editableId": null,
          "curve": 0,
          "format": {
            "textAlign": "left",
            "bold": false,
            "italic": false,
            "capital": false,
            "underline": false,
            "bulletSpan": false,
            "numericSpan": false
          },
          "spacing": {
            "anchor": "1",
            "letter": 0,
            "line": 0,
            "lineMultiplier": 1
          },
          "alignment": "4",
          "hasLayerEsffect": null
        }
      ]
    }
  ]